<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
  <PackageId>Ws.Maui.LocalDB.Sync</PackageId>
    <Version>1.0.0</Version>
    <Authors>Walter Soto</Authors>
    <Description>Offline-first sync library for .NET MAUI using local SQLite storage, conflict resolution, retry logic, and TTL policies.</Description>
    <PackageTags>maui;sync;sqlite;offline</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/waltersoto/Maui.LocalDB.Sync</RepositoryUrl>
    <PackageProjectUrl>https://github.com/waltersoto/Maui.LocalDB.Sync</PackageProjectUrl>
</PropertyGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Storage\Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>

</Project>
